// <auto-generated />
namespace E02_EF6_Migrations_Books_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class M03Book_New_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M03Book_New_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202207191923349_M03Book_New_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
